// src/routes/VideoRow.svelte
<script lang="ts">
	import type { VideoData } from "$lib/VideoData";

  interface Props {
    video: VideoData,
  }
  
  const { video }: Props = $props();
  const { title, channelName, videoUrl, channelUrl, thumbnailUrls } = video;
</script>


<div role='row' class='row'>
  <a role='cell' class='cell thumbnail-cell' href={videoUrl}>
    <img
      alt='Thumbnail'
      src={thumbnailUrls ? thumbnailUrls["default"].url : ""}/>
  </a>
  <a role='cell' class='cell' href={videoUrl}>
    {title}
  </a>
  <a role='cell' class='cell' href={channelUrl}>
    {channelName}
  </a>
</div>

// src/components/VideoRow.tsx
import { VideoData } from "../VideoData";

interface VideoRowProps {
  video: VideoData,
}

function VideoRow({ video }: VideoRowProps): JSX.Element {
  const { title, channelName, videoUrl, videoId, channelUrl, thumbnailUrls } = video;

  return (
    <div role='row' className='row'>
      <a role='cell' className='cell thumbnail-cell' href={videoUrl}>
        <img
          alt='Thumbnail'
          src={thumbnailUrls ? thumbnailUrls["default"].url : ""}/>
      </a>
      <a role='cell' className='cell' href={videoUrl}>
        {title}
      </a>
      <a role='cell' className='cell' href={channelUrl}>
        {channelName}
      </a>
    </div>
  )
}


export default VideoRow;
